export PS1="\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\$\[\033[00m\] "
export GL=/home/gl/ProjetGL

PATH=$GL/src/main/bin:"$PATH"
PATH=$GL/src/test/script:"$PATH"
PATH=$GL/src/test/script/launchers:"$PATH"
PATH=/usr/local/ima/bin:"$PATH"

export JAVA_HOME=/usr/lib/jvm/java-1.18.0-openjdk-amd64
export M2_HOME=/opt/maven
export MAVEN_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}

export PATH